### ISSUE TITLE
setup.py hardcoded to linux tensorflow

### ISSUE THREAD

**Issue by bbalaji-ucsd** [NervanaSystems/coach#103]
Fails to install when I try it on Mac

Complete output from command python setup.py egg_info:
    tensorflow-1.6.0-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "coach/setup.py", line 63, in <module>
        shell=True)
      File "/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pip install https://anaconda.org/intel/tensorflow/1.6.0/download/tensorflow-1.6.0-cp35-cp35m-linux_x86_64.whl']' returned non-zero exit status 1.

**Comment by galleibo-intel** [comment]
Hi,

Currently Mac is not officially supported by Coach. It was only tested on Ubuntu 16.04. 
Nevertheless, I don't see a reason for it not to work. The tensorflow version being installed is dependent on your machine. If no GPU is available (which is probably the case with the Mac), the [Intel Optimized Tensorflow](https://software.intel.com/en-us/articles/intel-optimization-for-tensorflow-installation-guide) version is used, otherwise, tensorflow-gpu is installed by default. 

Could you please try changing 'pip install https://anaconda.org/intel/tensorflow/1.6.0/download/tensorflow-1.6.0-cp35-cp35m-linux_x86_64.whl' in setup.py to 'pip install tensorflow==1.6.0', and see if it helps resolving the issue?

**Comment by bbalaji-ucsd** [comment]
Yes, this works. I reported the issue as I thought it was hard-coded to linux by mistake.

**Comment by galleibo-intel** [comment]
Sure. Thanks a lot for commenting that out. 
Officially supporting Mac is planned to be added in the future.
