### ISSUE TITLE
task_parameters should be explicit about what parameters it has rather than magically copying everything from args

### ISSUE THREAD

**Issue by zach-nervana** [NervanaSystems/coach#106]
see: https://github.com/NervanaSystems/coach/blob/horizontal_scaling/rl_coach/coach.py#L340

`task_parameters.__dict__ = add_items_to_dict(task_parameters.__dict__, args.__dict__)` is unnecessarily obscure. It means that there are properties of task parameters which are not enumerated in the class, and it is difficult to search for where they are getting set.

Would it be possible to remove this line, and replace it with explicit named values like is already used for parameters like `seed` and `use_cpu`?

**Comment by itaicaspi-intel** [comment]
The initial motivation was to have all the command line arguments (that are enumerated in the argparse object) available through the task parameters.

I agree that this is not the best way to do this. A better thing to do, in my opinion, was to add a sub-name that will be accessible through `task_parameters.command_line_parameters` or something similar, which will include all these parameters. 

It is also possible to explicitly define all the named values as you suggested. Although I think it would be error prone, since any new command line argument that will be added will need to be defined both through argparse and through the named value. 

With this said, both options sound better than the current approach.

**Comment by galleibo-intel** [comment]
Fixed with release 0.11.0.
