### ISSUE TITLE
How to get Coach working in a different framework?

### ISSUE THREAD

**Issue by dai-dao** [NervanaSystems/coach#12]
Hi,

I wanna ask how to get Coach to work with other frameworks like MXnet? I see the tensorflow_components  and neon_components folder, it's probably that I need to write my own components? 

It seems like that's all I need to do to include a new framework I think. I would probably send a PR supporting MXNet / Gluon at some later time.

**Comment by itaicaspi-intel** [comment]
Sure, it should be quite straight-forward to support MXnet (or any other python deep learning framework). 

As you said, most of the effort will be to create a copy of the tensorflow_components directory and change the tensorflow implementations to mxnet implementations. For testing the implementation, it is probably best to start with one of the simple algorithms such as DQN.
I would recommend going over the [design docs](http://coach.nervanasys.com/design/index.html) first, in order to get some understanding of how things are structured.

**Comment by itaicaspi-intel** [comment]
I am closing this issue for now. Let us know if you need any additional help with understanding the structure of Coach and adding MXNet.
