### ISSUE TITLE
Issues in Pong Experiment

### ISSUE THREAD

**Issue by mahsayedsalem** [NervanaSystems/coach#163]
![pong_stack](https://user-images.githubusercontent.com/11839520/50086051-90902000-0204-11e9-8a3a-868fc787904d.png)

Experiment: coach -r -p Atari_A3C -lvl pong
During my Pong experiment after around 2000 Episode it got stuck, now I'm at my 20681 episode and there's no improvement. Is there a valid reason for this to happen?

Here's a photo for my evaluation reward along the way.
![dashboard_pong](https://user-images.githubusercontent.com/11839520/50086347-65f29700-0205-11e9-819e-fc0d20df3b09.png)

**Comment by galleibo-intel** [comment]
Hi @mahsayedsalem,

The A3C algorithm should be run with several workers, training in parallel. Otherwise, the algorithm is not stable. So for instance you might consider trying `coach -p Atari_A3C -lvl pong -n 8`, which will invoke 8 workers asynchronously training the same network. 

Also, it might be better to look at the training curve with the x-axis set to steps instead of episodes. Note that for DQN, [for example](https://github.com/NervanaSystems/coach/tree/master/benchmarks/dqn), it takes ~4M steps to reach the maximal score.
