### ISSUE TITLE
Script for running Coach benchmarks automatically

### ISSUE THREAD

**Issue by anabwan** [NervanaSystems/coach#314]

**Comment by galleibo-intel** [comment]
To be eventually be run weekly on the CI. 

The script should run all benchmarks, from the Benchmarks folder, and for each one generate a PNG image of the benchmark, matching what we currently have today. 

In order to do so, the run commands, for each benchmark, should also have a flag to set the number of environment steps so to match the graph's X-axis. 

Dashboard should then be changed so to allow new command line arguments:
1. Adding signals to the graph
2. Setting the X-axis of the graph 
3. Saving a PNG image of the resulting graph.
