### ISSUE TITLE
Coach Designer for Visual programming creation of RL models by Drag-and-Drop 

### ISSUE THREAD

**Issue by developeralgo8888** [NervanaSystems/coach#317]
Feature request .  its very daunting task to learn several Machine Learning libraries every 2 to 3 months for  Data Scientists or new users .  Is Intel  working on a " COACH DESIGNER " similar to Microsoft's  Azure Machine Learning Studio which allows for Drag-and-Drop visual programming and then export the Code so that you can run the complete Model python script locally or externally. That would be a " GOD sent " Feature to anyone . Its exhausting for Data Scientists , Geeez !!!!!!

**Comment by galleibo-intel** [comment]
Hi @developeralgo8888, thanks a lot for the suggestion. It really would be a blessing if we could get reinforcement learning to work so easily with just a drag-and-drop interface. Unfortunately, this is not currently the case with Reinforcement Learning. Getting RL algorithms to work well on a new problem is often not an easy task. The state-of-the-art in RL is still not a push of a button getting it solve a new problem. It often requires a deeper understanding of the algorithm and the problem, in order to get it to work right. 

I don't necessarily agree with all of it, but there are some great parts in this [blog post](https://www.alexirpan.com/2018/02/14/rl-hard.html), which describes some of the current issues with RL today. 

Thanks a lot for the idea, but we will not be pursuing this direction at the moment.
