### ISSUE TITLE
where is the Dockerfile.carla_environment?

### ISSUE THREAD

**Issue by radeonwu** [NervanaSystems/coach#356]
Could not locate it under the docker/ sub folder.

**Comment by galnov** [comment]
@scttl do we have a Carla dockerfile?

**Comment by scttl** [comment]
@galnov no, nothing that was ever merged in per: https://github.com/NervanaSystems/coach/issues/204 (we needed GPU servers for testing in CI in order to bring Carla in).  I had started prepping a Carla dockerfile but the image ended up being huge owing to the large asssets and benchmarks files required > 10+GB if I recall correctly.

**Comment by galnov** [comment]
Closing this issue as there is no plan to add a Carla docker file.

**Comment by Amin-Tgz** [comment]
Hi,
If no plan for add CARLA docker, please remove [related part in document ](https://github.com/NervanaSystems/coach/tree/master/docker)to avoid confusing
Tnx

**Comment by galnov** [comment]
Removed.
