### ISSUE TITLE
BUG in Rainbow

### ISSUE THREAD

**Issue by eslambakr** [NervanaSystems/coach#373]
Hello,
Thanks for this amazing work.
I think there is a bug in Rainbow algorithm as the exploration is 0!

**Comment by gal-leibovich** [comment]
Hi @eslambakr,

Thanks a lot!

Rainbow's exploration policy is based on [NoisyNet](https://arxiv.org/abs/1706.10295) as can be seen [here](https://github.com/NervanaSystems/coach/blob/master/rl_coach/agents/rainbow_dqn_agent.py#L67). There is no printed exploration parameter just since there isn't one with this exploration policy.

I hope that this answers your question.

Gal

**Comment by eslambakr** [comment]
I see, thank you for the clarification
