### ISSUE TITLE
How to run Coach on multiple machines?

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [NervanaSystems/coach#47]
For example on 10 machines each having 20 CPU cores, to use 200 cores in total?

**Comment by itaicaspi-intel** [comment]
It's currently not possible with Coach.
Since we are using tensorflow as the backend, it could be done, but it will require some code changes.
Coach opens a new process for each worker and passes the addresses of the worker machines to tensorflow in `parallel_actor.py`. The addresses are currently hard coded to `localhost` here:
https://github.com/NervanaSystems/coach/blob/fff8c8f5688ab0700688262d851e91edc9d0f50b/coach.py#L316
To make this work as you want, we are missing some code that will run each of the processes on a different machine and update the addresses accordingly.

**Comment by AdamStelmaszczyk** [comment]
Thank you. 

Ok, so knowing the workers addresses one just have to set them in `worker_hosts`. Seems that SLURM sets nodes info in the environmental variables, so overall it should be easy to modify, following e.g. [this](https://github.com/deepsense-ai/tensorflow_on_slurm).
