### ISSUE TITLE
reusing and deploying  models?

### ISSUE THREAD

**Issue by jtoy** [NervanaSystems/coach#71]
Hi, I've trained a few models inside of coach now, love using coach to quickly test out algorithms.
After I've trained these models, is there a way to reuse or deploy these models in a live system?
Lets say I trained a few different algorithms with my env called "SolveMeaningOfLiveEnv" and PPO does best. Now I want to take the model and weights and use that in my production system with the coach system. I read through the docs but didn't see this kind of functionality, did I miss it?  Is it currently possible or are there plans to be able to do this?

**Comment by galleibo-intel** [comment]
Hi @jtoy , 
Coach allows saving the trained model weights every x seconds. These model weights can then be used to deploy your model to a real system using TensorFlow. Alternatively you can use the --evaluate flag, in order to run your model for inference directly from Coach, without further training the model. But I guess that you wouldn't want to run whole Coach framework on the real system, only for running inference with your model. Is using the trained model + weights directly with TensorFlow the thing that you're after?

**Comment by jtoy** [comment]
@galleibo-intel yes, im looking for using the trained model + weights directly with TensorFlow .
The use case is:  I want to generate custom stats, graphs, videos, etc during the inference phase, so I need to use the trained model with custom code. Some method or system to do this with coach could be very useful.

**Comment by galleibo-intel** [comment]
[TF Serving](https://www.tensorflow.org/serving/serving_basic) can be used to accomplish just that. currently Coach does not support it, yet.

**Comment by galnov** [comment]
The updated [Getting Started Guide](https://github.com/NervanaSystems/coach/blob/master/tutorials/0.%20Quick%20Start%20Guide.ipynb) shows how to load a checkpoint and run inference, and also how the trained agent can interact with the environment step by step.
One more example can be found in [issue 374](https://github.com/NervanaSystems/coach/issues/374).
Please reopen if additional support is needed.
