### ISSUE TITLE
dashboard requirements

### ISSUE THREAD

**Issue by jtoy** [NervanaSystems/coach#83]
on ubuntu 16.04 with latest tornado, the dashboard doesn't work,I get this error:
python3 dashboard.py 
2018-03-31 20:46:20,060 Starting Bokeh server version 0.12.7 (running on Tornado 5.0.1)
ERROR:__init__() got an unexpected keyword argument 'io_loop'

which specific version of tornado do you need with bokeh? It seems like this is a recent tornado issue:
https://github.com/bokeh/bokeh/issues/7308

**Comment by jtoy** [comment]
what virtual environment?
the version fixed it, added it to the requirements: https://github.com/NervanaSystems/coach/pull/84

**Comment by KuenstlicheIntelligenz** [comment]
If you have a look under Installation in the README.md

They deliver a full working(hopefully) virtual environment with the right versions to avoid conflicts and that nobody has to change his system or install any requirements to get coach to work.

You have to either activate it or call the interpreter in that directory. I'm not sure which version they deliver in the virtual env because i changed it alot myself.

**Comment by itaicaspi-intel** [comment]
Thanks guys, this is caused by a bug in the bokeh library where they are not enforcing the tornado version.
@jtoy your PR should fix this issue. I will merge it, thanks!
